version: "3"
services:
  zaga-web:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./zaga-web/
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - /usr/src/app/zaga-web/node_modules
      - ./zaga-web:/usr/src/app/zaga-web/
  config-server:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./config-server/
      dockerfile: Dockerfile.dev
    ports:
      - "8888:8888"
