spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mkitbs/git-config-repo
          username: mkitbusiness.solutions@gmail.com
          password: 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
          search-paths:
           - app-zaga
          skipSslValidation: true
server:
  port: 8888
